# Generated by Django 4.1 on 2022-12-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=50)),
                ('phone', models.IntegerField(help_text='89202341212')),
                ('msg', models.CharField(help_text='Текст заявки', max_length=250)),
                ('datacr', models.DateTimeField()),
                ('datasn', models.DateTimeField()),
            ],
        ),
    ]
