# Generated by Django 4.1 on 2022-12-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usrequest',
            name='sname',
        ),
        migrations.AlterField(
            model_name='usrequest',
            name='datacr',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usrequest',
            name='datasn',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usrequest',
            name='fname',
            field=models.CharField(max_length=40),
        ),
    ]
