# Generated by Django 4.1 on 2022-12-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_usrequest_sname_alter_usrequest_datacr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrequest',
            name='phone',
            field=models.CharField(help_text='Номер', max_length=16),
        ),
    ]
