# Generated by Django 4.1 on 2022-12-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_usrequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrequest',
            name='phone',
            field=models.CharField(help_text='Номер', max_length=16),
        ),
    ]
