# Generated by Django 4.1 on 2023-01-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_usrequest_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_pl', models.CharField(help_text='Текст заявки', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Редактор',
            },
        ),
        migrations.AlterModelOptions(
            name='usrequest',
            options={'verbose_name_plural': 'Заявки'},
        ),
    ]
