# Generated by Django 4.1 on 2023-01-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ustext_alter_usrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text='Цена', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Редактор',
            },
        ),
        migrations.DeleteModel(
            name='UsText',
        ),
    ]
