# Generated by Django 4.1 on 2023-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_usdata_delete_ustext'),
    ]

    operations = [
        migrations.AddField(
            model_name='usdata',
            name='fname',
            field=models.CharField(default=111, max_length=40),
            preserve_default=False,
        ),
    ]
