# Generated by Django 4.1 on 2023-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usdata_fname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usdata',
            name='fname',
        ),
        migrations.AddField(
            model_name='usdata',
            name='chapter_tx',
            field=models.CharField(default=111, help_text='Раздел', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usdata',
            name='qweasdzxc',
            field=models.CharField(default=111, help_text='Текст', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usdata',
            name='title_tx',
            field=models.CharField(default=1, help_text='Заголовок', max_length=1000),
            preserve_default=False,
        ),
    ]
