# Generated by Django 4.1 on 2023-01-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_chapter_tx_usdata_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdata',
            name='text',
            field=models.TextField(help_text='Текст', max_length=1000),
        ),
    ]
