# Generated by Django 4.1 on 2023-01-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_usdata_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usdata',
            name='chapter',
            field=models.CharField(max_length=1000, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='usdata',
            name='price',
            field=models.CharField(max_length=1000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='usdata',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='usdata',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Заголовок'),
        ),
    ]
