# Generated by Django 4.1 on 2023-01-29 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_usdata_chapter_alter_usdata_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usdata',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
