# Generated by Django 4.1 on 2023-01-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_services_delete_usdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
