# Generated by Django 4.1 on 2023-01-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_services_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('about', models.TextField(max_length=100, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Раздел сотрудники',
                'verbose_name_plural': 'Раздел сотрудники',
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Раздел услуг', 'verbose_name_plural': 'Раздел услуги'},
        ),
    ]
