# Generated by Django 4.1 on 2023-01-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_staff_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст')),
                ('href', models.CharField(max_length=40, verbose_name='Ссылка')),
                ('img', models.ImageField(upload_to='feedback/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Раздел отзывы',
            },
        ),
        migrations.AlterField(
            model_name='staff',
            name='about',
            field=models.TextField(max_length=1000, verbose_name='О сотруднике'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='img',
            field=models.ImageField(upload_to='staff/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Имя'),
        ),
    ]
