# Generated by Django 4.1 on 2023-01-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_feedback_alter_staff_about_alter_staff_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='num',
            field=models.CharField(default=1, max_length=1000, verbose_name='Расположение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
    ]
